### ISSUE TITLE
Module name including 'dash' and import issues

### ISSUE THREAD

**Issue by empireshades** [jarroddowalter/ultimate-pai-gow#1]
1. `import pygow-poker` does not work in the way you'd expect because of the dash in the module name so I had to resort to using importlib as per this [guidance](https://stackoverflow.com/questions/8350853/how-to-import-module-when-module-name-has-a-dash-or-hyphen-in-it). Would it be possible to rename the module to avoid this?

2. Also, when trying to import, I get this error:
```
File ~/labs/venv/std310/lib/python3.10/site-packages/pygow-poker/__init__.py:7
      4 from rich.console import Console
      5 console = Console()
----> 7 import game_configs
      8 from game import DECK, format_hand, read_hand, determine_winner, add_bet, determine_winnings, sort_dict
      9 from house_strat import house_strat

ModuleNotFoundError: No module named 'game_configs'
```

which seems to be some kind of pathing issue because the local file game_configs.py definitely exists when I install via pip on command line. I do notice this file seems to be missing in the latest version [here](https://github.com/jarroddowalter/pygow-poker/tree/master/src/pygow-poker) yet it's still referenced in `game.py`. Any guidance here? 

Thanks for your work on this.

**Comment by jarroddowalter** [comment]
Hi! Very surprised to get a comment on this project because it was just a fun personal project to help me learn python. I have set it aside to focus on other work but planning on fleshing out more features. Right now it's very broken because I was working on game templates last I touched it so I am positive the pathing is broken.

You have motivated me to pick this back up ASAP so I will try and get this back to a working state.

**Comment by empireshades** [comment]
I had spent a few hours at a Pai Gow table and was inspired to look for python utils that would help emulate game play 😊

I'd appreciate whatever you can do to get it working again. I'll take a look myself as well.

Thanks @jarroddowalter

**Comment by empireshades** [comment]
I actually ended up forking your repo and modified it to get it working for my purposes, centered mainly around common.py, the split strategies, and face_up.py. I tried to honor the essence of what I thought you were going for. You can take a look at the [changes](https://github.com/jarroddowalter/pygow-poker/compare/master...empireshades:pygow-poker:master) and I'd be willing to submit a pull request if you'd like. Otherwise I can just close this issue. Thanks.

**Comment by jarroddowalter** [comment]
Thank you @empireshades!

**Comment by empireshades** [comment]
Hi @jarroddowalter, let me know if you want me to do the pull request. Otherwise I'll close this out. Thanks.

**Comment by jarroddowalter** [comment]
Merged!
